# Generated by Django 3.0 on 2020-12-31 06:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mainapp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=50)),
                ('category', models.CharField(default='', max_length=50)),
                ('subcategory', models.CharField(default='', max_length=50)),
                ('desc', models.CharField(max_length=300)),
                ('price', models.IntegerField(default=0)),
                ('image', models.ImageField(default='', upload_to='shop/images')),
                ('pub_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('quotation_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=50, verbose_name='Last Name')),
                ('email', models.EmailField(max_length=60, verbose_name='Email')),
                ('quotation', models.CharField(blank=True, max_length=3000)),
                ('customization', models.CharField(max_length=3000)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('quotation_date', models.DateTimeField(auto_now=True, verbose_name='Quotation Date')),
                ('author_comment', models.CharField(blank=True, max_length=3000, null=True)),
                ('product', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mainapp.Product')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=models.SET(mainapp.models.get_sentinel_user), to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('image_id', models.AutoField(primary_key=True, serialize=False)),
                ('img_file', models.ImageField(default='', upload_to='shop/images')),
                ('upload_date', models.DateTimeField(auto_now=True, verbose_name='Upload Date')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Product')),
            ],
        ),
    ]
